### PR TITLE
Add time and timezone types.

### PR DESCRIPTION
**Pull request by koden-km**
Should I use http://php.net/manual/en/datetimezone.getoffset.php for parsing string named timezones or just support numeric offsets?

### CODE REVIEW

**Comment by jmalloc** [comment]
Whatever you need for your use-case. I don't see any problem with parsing the strings in the Doctrine type.

**Comment by koden-km** [comment]
No need to parse the string timezones, it doesn't really make sense here.

Which versions of PHP should we be supporting now? all the 5.x versions are failing builds because dependencies have moved on to newer PHP versions.

**Comment by jmalloc** [comment]
7.0+

**Comment by koden-km** [comment]
Ok i think this is ready now. Run your retinas over it and let me know what you find.

**Pull request merged**
